# Generated by Django 5.2.6 on 2025-09-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cajero', 'Cajero')], default='mesero', max_length=10),
        ),
    ]
